### ISSUE TITLE
Add GH action to ensure this workflow runs forever

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/iso-10303-stepmod-annotate#2]
<img width="1198" alt="Screen Shot 2022-09-07 at 2 37 53 PM" src="https://user-images.githubusercontent.com/11865/188806454-e8430ac8-ea9d-4e16-838d-40547a87a390.png">

**Comment by CAMOBAP** [comment]
Done, I will observe a couple runs before closing this one

**Comment by CAMOBAP** [comment]
Works
