### ISSUE TITLE
Update source repo

### ISSUE THREAD

**Issue by TRThurman** [metanorma/iso-10303-stepmod-annotate#5]
The source repo needs updating to wg12-stepdev.
As this is a daily update, TF1 needs to discuss which branch to extract from:
options:
main,
hotfix/TCSC410303-1374-smrlv9-rc5,
smrlv10.
 
Initial suggestion is hotfix/TCSC410303-1374-smrlv9-rc5 because that corresponds to published SMRLv9.
develop has known xml issues because of the WG12 workflow.

**Comment by ronaldtse** [comment]
@TRThurman I cannot find the branch `hotfix/TCSC410303-1374-smrlv9-rc5` in this repository. `main` and `SMRLv10` exist.

The particular repo location and branch is at:
* https://sd.iso.org/bitbucket-pilot/projects/ISOTC184SC4/repos/wg12-stepdev/browse?at=refs%2Fheads%2FSMRLv10

Clone location:
* https://sd.iso.org/bitbucket-pilot/scm/isotc184sc4/wg12-stepdev.git

**Comment by ronaldtse** [comment]
As described https://github.com/metanorma/iso-10303-stepmod-wg12/issues/3 :

@TRThurman the branch `hotfix/TCSC410303-1374-smrlv9-rc5` is not available from wg12-stepdev. I believe we should use the `SMRLv9` tag which includes the said hotfix at ticket 1374:

https://sd.iso.org/bitbucket-pilot/projects/ISOTC184SC4/repos/wg12-stepdev/browse?at=refs%2Fheads%2FSMRLv9

<img width="1022" alt="Screenshot 2023-05-10 at 5 25 54 PM" src="https://github.com/metanorma/iso-10303-stepmod-wg12/assets/11865/b773d506-6df1-4a25-8308-5bb3c205295b">

I will change the branch to `SMRLv9`.
