### ISSUE TITLE
Keep alive workflow not working

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/iso-10303-stepmod-annotate#8]
The keep alive workflow has been "timed out".

<img width="974" alt="Screenshot 2023-10-24 at 9 17 52 AM" src="https://github.com/metanorma/iso-10303-stepmod-annotate/assets/11865/b0e6ae09-7e3e-4238-ad95-f78f48aa7f07">

**Comment by CAMOBAP** [comment]
Wrong cron date condition was used

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
